export const FETCH_SHIPMENTS = 'SHIPMENTS/FETCH_SHIPMENTS';
export const FETCH_SHIPMENTS_ERROR = 'SHIPMENTS/FETCH_SHIPMENTS_ERROR';
export const FETCH_SHIPMENTS_SUCCESS = 'SHIPMENTS/FETCH_SHIPMENTS_SUCCESS';
export const FETCH_SHIPMENTS_REQUESTED = 'SHIPMENTS/FETCH_SHIPMENTS_REQUESTED';

export const SET_SHIPMENT_BOXES = 'SHIPMENTS/SET_SHIPMENT_BOXES';

export const FILTER_LIST = 'SHIPMENTS/FILTER_LIST';